name: Base Python Setup
description: 'Set up Python environment'

inputs:
  environment:
    description: 'Environment to set up'
    required: true
    default: 'dev'

runs:
  using: composite
  steps: 
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.8'
      
    - name: Setup a local virtual environment (if no poetry.toml file)
      run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{inputs.environment}}-${{ hashFiles('poetry.lock') }}

    - name: Setup dependencies
      run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            poetry install --with dev --no-root
          else
            poetry install --no-root
          fi