name: Release

on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
      
jobs:
  bump-version:
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'bump:')
    runs-on: ubuntu-latest
      
    outputs:
      version: ${{ steps.cz.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pypi-publish:
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'bump:') && needs.bump-version.outputs.version != ''
    runs-on: ubuntu-latest
    needs: bump-version

    environment:
      name: pypi
      url: https://pypi.org/p/alvoc
      
    permissions:
      id-token: write 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
    - name: Base Setup
      uses: ./.github/workflows/actions/setup-base
      with:
        environment: prod
        shell: bash

    - name: Build the package
      shell: bash
      run: |
        uv build

    - name: Publish the package
      shell: bash
      run: |
          uv publish

  publish-docker:
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'bump:') && needs.bump-version.outputs.version != ''
    runs-on: ubuntu-latest
    needs: bump-version

    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and Publish Docker Image
        uses: ./.github/workflows/actions/package-image
        with:
          image_name: ${{ github.repository }}
